
class AppStrings{
  static String appName = "Barbearia do Fael",
  bestBarber = "O melhor barbeiro\n Aplicativo de agendamento",
  welcomeBack = "Bem vindo de Volta",
  weAreExcited = "estamos entusiasmados por ter você de volta",
  signupNow = "Cadastre-se agora e comece a explorar tudo o que nosso aplicativo tem a oferecer",
  email = "Email",
  emailHint = "Digite Seu Email...",
  password = "Senha",
  passwordHint = "Digite Sua senha",
  fullName = "Nome Completo",
  fullNameHint = "Digite seu Nome",
  confirmePassword = "Confirme sua Senha",
  forgetPassword = "Esqueceu sua Senha?",
  login = "Entrar",
  signup = "Cadastrar",
  welcome = "Bem Vindo",
  alreadyHaveAccount = "Você tem uma conta?",
  dontHaveAccount = "Não tem uma conta?",
  titleService = "Serviços",
  service1 = "pezinho",
  service2 = "Barba",
  service3 = "Barboterapia",
  service4 = "Corte Degradê",
  service5 = "Corte Navalhado",
  service6 = "Corte Social",
  service7 = "Corte todo na Tesoura",
  service8 = "Hidratação",
  service9 = "Relaxamento",
  service10 = "Sombrancelha",
  category = "Categoria",
  settings = "Configurações",
  barber = "Barbeiro login",
  changePassword = "Alterar Senha",
  termConditions = "Termo e Condições",
  signout = "Sair";


}

