// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDma1xiaWf6weJyIfFyzQMNQECBM8Mbq1k',
    appId: '1:55763303614:web:6cfad10bacfc47491872ef',
    messagingSenderId: '55763303614',
    projectId: 'flutterbarbeariaagendamentos',
    authDomain: 'flutterbarbeariaagendamentos.firebaseapp.com',
    storageBucket: 'flutterbarbeariaagendamentos.appspot.com',
    measurementId: 'G-1X1ZYDEPYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD31NKqheOI7I8zMOl5-QiueNFcfRkp1ew',
    appId: '1:55763303614:android:7ad6c4648c2ac4f41872ef',
    messagingSenderId: '55763303614',
    projectId: 'flutterbarbeariaagendamentos',
    storageBucket: 'flutterbarbeariaagendamentos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv2Xyo6oP9OF2mjSSCbmD2L7TvFGXqMb4',
    appId: '1:55763303614:ios:469836cbba3410041872ef',
    messagingSenderId: '55763303614',
    projectId: 'flutterbarbeariaagendamentos',
    storageBucket: 'flutterbarbeariaagendamentos.appspot.com',
    iosClientId: '55763303614-7e54os9hmt0qah7et5oeeame07af2u4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendfael',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv2Xyo6oP9OF2mjSSCbmD2L7TvFGXqMb4',
    appId: '1:55763303614:ios:7c00d81817471f3d1872ef',
    messagingSenderId: '55763303614',
    projectId: 'flutterbarbeariaagendamentos',
    storageBucket: 'flutterbarbeariaagendamentos.appspot.com',
    iosClientId: '55763303614-agi9u34og6dte80ntp7bj2996902i452.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendfael.RunnerTests',
  );
}
